.TH MORSE_CLI 1 "April 2026" "morse-cli 1.16.4" "User Commands"
.SH NAME
morse_cli \- Morse Micro Wi\-Fi HaLow userspace control utility
.SH SYNOPSIS
.B morse_cli
.RI [ options ]
.I command
.RI [ arguments ]
.SH DESCRIPTION
.B morse_cli
is a command\-line utility for controlling and managing Morse Micro
Wi\-Fi HaLow (802.11ah) wireless devices. It supports communication via
netlink (NL80211), UART SLIP, and TCP SLIP transports.
.SH OPTIONS
Run
.B morse_cli \-\-help
for a list of available commands and options.
.SH SEE ALSO
.BR wpa_supplicant_s1g (8),
.BR hostapd_s1g (8)
.SH AUTHOR
Morse Micro Pty. Ltd.
